### ISSUE TITLE
Incorrect number of event occurrences

### ISSUE THREAD

**Issue by charanya15** [benignware/schedulable#14]
I created an event and then scheduled it as follows
schedule_attributes = {date: Date.today, time: Time.now + 20.minutes, rule: 'daily', count: 5)}

I am saving the occurrences in EventOccurrences table.
I am expecting 5 Event Occurrences to be saved, but instead I am getting only 4 EventOccurrences.

I went through the code, and in 'acts_as_schedulable.rb', there was a condition which said, occurrence_date.to_time < max_date,

In this case max_date will be the 5th occurrence date. But this condition fails bcos it is not less than the max_date

Any help would be appreciated, if this is the expected behaviour, or my understanding about the way it works is wrong.

**Comment by pauldatta** [comment]
@charanya15 What happens if you list all event occurrences giving the last date as a parameter?

**Comment by rexblack** [comment]
Many thanks for digging into this. You may have encountered a bug. I'll try to reproduce this and give you notice shortly.
