### ISSUE TITLE
Event has_many :event_occurrences. How to?

### ISSUE THREAD

**Issue by yshmarov** [benignware/schedulable#31]
With the default setup, 
the Event can call the `= event.schedule`
&
the EventOccurrence can call the `= event_occurrence.schedulable_id`
=>
How do we call the parent Event from EventOccurrence?
Like `= event_occurrence.schedule.event.name`

**Comment by rexblack** [comment]
Hi and thanks for your question. 
Did you create your occurrence model with the generator? 
You should be able to call event_occurrence.schedulable to get the corresponding event instance then. Did you try this?
Thanks and regards, 
Rafael

**Comment by rexblack** [comment]
And please, checkout master because it contains some bugfixes that haven't been released yet and may affect your issue

**Comment by yshmarov** [comment]
Thank you!
