### ISSUE TITLE
EventOccurrence duplication upon editing Event

### ISSUE THREAD

**Issue by arzezak** [benignware/schedulable#33]
Persisting occurrences works fine. Thing is upon editing the date of an Event instance a new EventOccurrence is persisted instead of modifying an existing one. I've setup Schedulable in a new Rails 5 application and the same thing happens.

**Comment by rexblack** [comment]
Hi. Thanks for reporting. Does this happen to all rules or only a specific one, i.e `singular`?
If you haven't already, please also try out master branch since it's a few issues ahead of the recent release.

**Comment by arzezak** [comment]
Thanks. I've been testing with weekly rules only. Almost sure I've been using the master branch. I'll double check that. Ruby 2.4.0. Rails 5.0.1.

**Comment by arzezak** [comment]
I've been testing this. There are some event_occurrences from the collection tied to the event that are being deleted, some are not. Also, the callback should edit existing occurrences I think, instead of destroying them. Exactly half of them are being destroyed.

**Comment by maahipal** [comment]
Is this resolved?
