### ISSUE TITLE
All Schedule attributes value nil rails 4.1.12

### ISSUE THREAD

**Issue by ats-developer** [benignware/schedulable#34]
I am using schedule 0.0.10. No matter whatever values I assign to schedule object it does not takes any value and all attributes are nil.

`schedule = Schedule.create(schedulable: Activity.last, rule: 'weekly', interval: 2, date: Date.today, time: (Time.now + 1000)`

Above line does not saves schedule and gives error that rule can't be blank and time can't be blank and all values of schedule object are `nil`.

Any help will be great.
Thanks.

**Comment by jeedee** [comment]
How did you fix your issue?
