### ISSUE TITLE
Incorrect day labels in simple_form custom input checkboxes

### ISSUE THREAD

**Issue by DCas** [benignware/schedulable#5]
When creating schedules with weekly and monthly recurrence rules, the checkboxes in the simple_form custom input are incorrectly labeled.  The checkbox labeled 'Sunday' has value :monday, 'Monday' has value :tuesday, etc.

Inconsistency in the start of the week returned by Time::DAYS_INTO_WEEK and I18n.t("date.day_names") is causing the problem.  Changing the date.day_names translation to ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] is a quick fix but doesn't solve the issue across locales and might have effects elsewhere.

**Comment by rexblack** [comment]
Thanks for reporting the issue. I already fixed it some time ago but didn't push. Oh no ;-) 
It should now be fixed with current release v0.0.7. Please reopen the issue, if you encounter any need for further editing.
