### ISSUE TITLE
Updating the ReadMe!

### ISSUE THREAD

**Issue by Rodney-QAGeek** [benignware/schedulable#7]
First and foremost, Thanks for creating this gem, It's really useful!

I ran into a little trouble getting my occurrences working properly so I thought I'd share the steps here incase it was worth updating on the Readme. I've had to discover, by looking at your demo project, that it's necessary to create the following code changes:

The first is that your _occurrence model belongs to :scheduable and not your model as the current Readme indicates. The snippet below works!
```Ruby
class EventOccurrence < ActiveRecord::Base
  belongs_to :schedulable, polymorphic: true
end
```
The next is that a migration is required that adds a schedulable reference to your _occurrence table.
```Ruby
def change
  add_reference :event_occurrences, :schedulable, polymorphic: true, index: true
end
```
And the last is that sometimes your table name is too long to create an index automatically and you receive an error message that states "Index name on table 'event_occurrences' is too long; the limit is 63 characters".

In these instances it's better if you drop the "index: true" and create a separate migration to add the index with a shorter name.
```Ruby
class AddReferencesIndex < ActiveRecord::Migration
  add_index "event_occurrences", ["schedulable_type", "schedulable_id"], name: "index_event_occurrences_on_schedulable_type_schedulable_id"
end
```

I hope this helps save someone else some time.

**Comment by rexblack** [comment]
Hi Rodney, 
thank you very much for your advice. This is really an important help! Besides changing the Readme, also the occurrence_generator should support the required migrations. I'll take a look at this shortly. If you'd like to create a pull request, you're welcome!

**Comment by cderche** [comment]
Thank you! This helped resolve the issues I was having!

**Comment by rexblack** [comment]
I'm closing this, since this should be fixed by the occurrence-generator and improved documentation about it. Thanks for contributing your findings.
